point_cloud_topic: "/lidar_pc"
map_frame_id: "/ground_truth"
robot_base_frame_id: "/root"
robot_pose_with_covariance_topic: "/root"
robot_pose_cache_size: 200
track_point_frame_id: "root"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
